name: Markdownlint

on:
  push:
    branches:
      - draft-v6
      - draft-v7
      - draft-v8
    paths:
      - "standard/*.md"
      - ".markdownlint.json"
  pull_request:
    paths:
      - "standard/*.md"
      - ".markdownlint.json"
  workflow_dispatch:
    inputs:
      reason:
        description: 'The reason for running the workflow'
        required: true
        default: 'Manual run'

jobs:
  lint:

    runs-on: ubuntu-latest
    permissions:
        statuses: write

    steps:
    - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5
    - name: Use Node.js
      uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
      with:
        node-version: 16.x
    - name: Run Markdownlint
      run: |
        echo "::add-matcher::.github/workflows/markdownlint-problem-matcher.json"
        npm i -g markdownlint-cli
        markdownlint "standard/*.md"
